# Generated by Django 4.2.3 on 2023-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
